worker_processes auto;

events {
  worker_connections 1024;
}

stream {
  log_format stream_json escape=json '{'
    '"ts":"$time_iso8601",'
    '"remote_addr":"$remote_addr",'
    '"bytes_sent":$bytes_sent,'
    '"bytes_received":$bytes_received,'
    '"session_time":$session_time,'
    '"upstream_addr":"$upstream_addr"'
  '}';

  access_log /var/log/nginx/access.log stream_json;
  error_log /var/log/nginx/error.log warn;

  upstream proxy_backend {
    server squid:3128;
  }

  server {
    listen 8443 ssl;
    proxy_pass proxy_backend;

    ssl_certificate /etc/nginx/certs/crt.pem;
    ssl_certificate_key /etc/nginx/certs/crt.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
  }
}

http {
  access_log /var/log/nginx/http-access.log;
  error_log /var/log/nginx/http-error.log warn;

  server {
    listen 8080;
    location /healthz {
      return 200 'ok';
      add_header Content-Type text/plain;
    }
  }
}
